import { Type, Square } from "lucide-react";

export const ANIMATIONS_DATA = {
  "text-animations": {
    title: "Text Animations",
    icon: <Type size={18} />,
    items: [
      { id: "blur-text", name: "Blur Text" },
      { id: "per-letter-blur", name: "Per Letter Blur" },
      { id: "split-reveal", name: "Split Reveal" },
      { id: "kinetic-reveal", name: "Kinetic Reveal" },
      { id: "narrative-text", name: "Narrative Text" },
      { id: "wave-text", name: "Wave Text" },
      { id: "elastic-text", name: "Elastic Text" },
      { id: "gravity-drop", name: "Gravity Drop" },
      { id: "typewriter", name: "Typewriter" },
      { id: "counter", name: "Counter" },
      { id: "ascii-morph", name: "ASCII Morph" },
      { id: "data-stream-decode", name: "Data Stream Decode" },
      { id: "blueprint-wireframe", name: "Blueprint Wireframe Text" },
      { id: "led-text", name: "Led Text" },
      { id: "scanline-reveal", name: "Scanline Reveal" },
      { id: "on-hover-swap", name: "On Hover Swap" },
      { id: "per-letter-hover", name: "Per Letter Hover" },
      { id: "per-word-hover", name: "Per Word Hover" },
      { id: "soft-glow-pulse", name: "Soft Glow Pulse" },
      { id: "gradient-flow", name: "Gradient Flow" },
      { id: "wednesday", name: "Wednesday" },
      { id: "severance", name: "Severance" },
      { id: "glitch-stabilize", name: "Glitch Stabilize" },
      { id: "distored-text", name: "Distorted Text" },
      { id: "word-morph", name: "Word Morph" },
    ],
  },
  components: {
    title: "Components",
    icon: <Square size={18} />,
    items: [
      { id: "code-grid", name: "Code Grid" },
      { id: "border-shard", name: "Border Shard" },
      { id: "gradient-border", name: "Gradient Border" },
      { id: "gradient-card", name: "Gradient Card" },
      { id: "scramble-screen", name: "Scramble Screen" },
      { id: "ludwig-hover", name: "Ludwig Hover" },
      { id: "glow-stars", name: "Glow Stars" },
      { id: "purple-trails", name: "Purple Trails" },
    ],
  },
};
